/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_RestoreOptions */

#ifndef _Included_org_forstdb_RestoreOptions
#define _Included_org_forstdb_RestoreOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_RestoreOptions
 * Method:    newRestoreOptions
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_RestoreOptions_newRestoreOptions
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_forstdb_RestoreOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_RestoreOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
