/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_RemoveEmptyValueCompactionFilter */

#ifndef _Included_org_forstdb_RemoveEmptyValueCompactionFilter
#define _Included_org_forstdb_RemoveEmptyValueCompactionFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_RemoveEmptyValueCompactionFilter
 * Method:    createNewRemoveEmptyValueCompactionFilter0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_RemoveEmptyValueCompactionFilter_createNewRemoveEmptyValueCompactionFilter0
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
