/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_ImportColumnFamilyOptions */

#ifndef _Included_org_forstdb_ImportColumnFamilyOptions
#define _Included_org_forstdb_ImportColumnFamilyOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_ImportColumnFamilyOptions
 * Method:    newImportColumnFamilyOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_ImportColumnFamilyOptions_newImportColumnFamilyOptions
  (JNIEnv *, jclass);

/*
 * Class:     org_forstdb_ImportColumnFamilyOptions
 * Method:    moveFiles
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_ImportColumnFamilyOptions_moveFiles
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_ImportColumnFamilyOptions
 * Method:    setMoveFiles
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_ImportColumnFamilyOptions_setMoveFiles
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_ImportColumnFamilyOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_ImportColumnFamilyOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
