/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_LiveFileMetaData */

#ifndef _Included_org_forstdb_LiveFileMetaData
#define _Included_org_forstdb_LiveFileMetaData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_LiveFileMetaData
 * Method:    newLiveFileMetaDataHandle
 * Signature: ([BIILjava/lang/String;Ljava/lang/String;JJJ[BI[BIJZJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_LiveFileMetaData_newLiveFileMetaDataHandle
  (JNIEnv *, jobject, jbyteArray, jint, jint, jstring, jstring, jlong, jlong, jlong, jbyteArray, jint, jbyteArray, jint, jlong, jboolean, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
