/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_Slice */

#ifndef _Included_org_forstdb_Slice
#define _Included_org_forstdb_Slice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_Slice
 * Method:    data0
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_forstdb_Slice_data0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_Slice
 * Method:    createNewSlice0
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Slice_createNewSlice0
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_forstdb_Slice
 * Method:    createNewSlice1
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Slice_createNewSlice1
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_forstdb_Slice
 * Method:    clear0
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Slice_clear0
  (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     org_forstdb_Slice
 * Method:    removePrefix0
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Slice_removePrefix0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_forstdb_Slice
 * Method:    disposeInternalBuf
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Slice_disposeInternalBuf
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
