/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_AbstractCompactionFilterFactory */

#ifndef _Included_org_forstdb_AbstractCompactionFilterFactory
#define _Included_org_forstdb_AbstractCompactionFilterFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_AbstractCompactionFilterFactory
 * Method:    createNewCompactionFilterFactory0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_AbstractCompactionFilterFactory_createNewCompactionFilterFactory0
  (JNIEnv *, jobject);

/*
 * Class:     org_forstdb_AbstractCompactionFilterFactory
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_AbstractCompactionFilterFactory_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
