/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_SstFileManager */

#ifndef _Included_org_forstdb_SstFileManager
#define _Included_org_forstdb_SstFileManager
#ifdef __cplusplus
extern "C" {
#endif
#undef org_forstdb_SstFileManager_RATE_BYTES_PER_SEC_DEFAULT
#define org_forstdb_SstFileManager_RATE_BYTES_PER_SEC_DEFAULT 0LL
#undef org_forstdb_SstFileManager_DELETE_EXISTING_TRASH_DEFAULT
#define org_forstdb_SstFileManager_DELETE_EXISTING_TRASH_DEFAULT 1L
#undef org_forstdb_SstFileManager_MAX_TRASH_DB_RATION_DEFAULT
#define org_forstdb_SstFileManager_MAX_TRASH_DB_RATION_DEFAULT 0.25
#undef org_forstdb_SstFileManager_BYTES_MAX_DELETE_CHUNK_DEFAULT
#define org_forstdb_SstFileManager_BYTES_MAX_DELETE_CHUNK_DEFAULT 67108864LL
/*
 * Class:     org_forstdb_SstFileManager
 * Method:    newSstFileManager
 * Signature: (JJJDJ)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileManager_newSstFileManager
  (JNIEnv *, jclass, jlong, jlong, jlong, jdouble, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    setMaxAllowedSpaceUsage
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileManager_setMaxAllowedSpaceUsage
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    setCompactionBufferSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileManager_setCompactionBufferSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    isMaxAllowedSpaceReached
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_SstFileManager_isMaxAllowedSpaceReached
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    isMaxAllowedSpaceReachedIncludingCompactions
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_SstFileManager_isMaxAllowedSpaceReachedIncludingCompactions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    getTotalSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileManager_getTotalSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    getTrackedFiles
 * Signature: (J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_forstdb_SstFileManager_getTrackedFiles
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    getDeleteRateBytesPerSecond
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileManager_getDeleteRateBytesPerSecond
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    setDeleteRateBytesPerSecond
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileManager_setDeleteRateBytesPerSecond
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    getMaxTrashDBRatio
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_forstdb_SstFileManager_getMaxTrashDBRatio
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    setMaxTrashDBRatio
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileManager_setMaxTrashDBRatio
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_forstdb_SstFileManager
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileManager_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
