/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_OptionsUtil */

#ifndef _Included_org_forstdb_OptionsUtil
#define _Included_org_forstdb_OptionsUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_OptionsUtil
 * Method:    loadLatestOptions
 * Signature: (JLjava/lang/String;JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_OptionsUtil_loadLatestOptions
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_forstdb_OptionsUtil
 * Method:    loadOptionsFromFile
 * Signature: (JLjava/lang/String;JLjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_OptionsUtil_loadOptionsFromFile
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject);

/*
 * Class:     org_forstdb_OptionsUtil
 * Method:    getLatestOptionsFileName
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_forstdb_OptionsUtil_getLatestOptionsFileName
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_forstdb_OptionsUtil
 * Method:    readTableFormatConfig
 * Signature: (J)Lorg/forstdb/TableFormatConfig;
 */
JNIEXPORT jobject JNICALL Java_org_forstdb_OptionsUtil_readTableFormatConfig
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
