/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_WriteOptions */

#ifndef _Included_org_forstdb_WriteOptions
#define _Included_org_forstdb_WriteOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_WriteOptions
 * Method:    newWriteOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_WriteOptions_newWriteOptions
  (JNIEnv *, jclass);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    copyWriteOptions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_WriteOptions_copyWriteOptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setSync
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setSync
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    sync
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_sync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setDisableWAL
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setDisableWAL
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    disableWAL
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_disableWAL
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setIgnoreMissingColumnFamilies
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setIgnoreMissingColumnFamilies
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    ignoreMissingColumnFamilies
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_ignoreMissingColumnFamilies
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setNoSlowdown
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setNoSlowdown
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    noSlowdown
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_noSlowdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setLowPri
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setLowPri
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    lowPri
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_lowPri
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    memtableInsertHintPerBatch
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_WriteOptions_memtableInsertHintPerBatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_WriteOptions
 * Method:    setMemtableInsertHintPerBatch
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteOptions_setMemtableInsertHintPerBatch
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
