/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_SstFileWriter */

#ifndef _Included_org_forstdb_SstFileWriter
#define _Included_org_forstdb_SstFileWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    newSstFileWriter
 * Signature: (JJJB)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileWriter_newSstFileWriter__JJJB
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyte);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    newSstFileWriter
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileWriter_newSstFileWriter__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    open
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_open
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    put
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_put__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    put
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_put__J_3B_3B
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    putDirect
 * Signature: (JLjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_putDirect
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    fileSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SstFileWriter_fileSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    merge
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_merge__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    merge
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_merge__J_3B_3B
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_delete__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    delete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_delete__J_3B
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    finish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_finish
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_SstFileWriter
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_SstFileWriter_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
