/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_WriteBufferManager */

#ifndef _Included_org_forstdb_WriteBufferManager
#define _Included_org_forstdb_WriteBufferManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_WriteBufferManager
 * Method:    newWriteBufferManager
 * Signature: (JJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_WriteBufferManager_newWriteBufferManager
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_forstdb_WriteBufferManager
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteBufferManager_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
