/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_WriteBatchTest */

#ifndef _Included_org_forstdb_WriteBatchTest
#define _Included_org_forstdb_WriteBatchTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_WriteBatchTest
 * Method:    getContents
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_forstdb_WriteBatchTest_getContents
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
