/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_Env */

#ifndef _Included_org_forstdb_Env
#define _Included_org_forstdb_Env
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_Env
 * Method:    getDefaultEnvInternal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Env_getDefaultEnvInternal
  (JNIEnv *, jclass);

/*
 * Class:     org_forstdb_Env
 * Method:    setBackgroundThreads
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Env_setBackgroundThreads
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    getBackgroundThreads
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_org_forstdb_Env_getBackgroundThreads
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    getThreadPoolQueueLen
 * Signature: (JB)I
 */
JNIEXPORT jint JNICALL Java_org_forstdb_Env_getThreadPoolQueueLen
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    incBackgroundThreadsIfNeeded
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Env_incBackgroundThreadsIfNeeded
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    lowerThreadPoolIOPriority
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Env_lowerThreadPoolIOPriority
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    lowerThreadPoolCPUPriority
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Env_lowerThreadPoolCPUPriority
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_forstdb_Env
 * Method:    getThreadList
 * Signature: (J)[Lorg/forstdb/ThreadStatus;
 */
JNIEXPORT jobjectArray JNICALL Java_org_forstdb_Env_getThreadList
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
