/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_TimedEnv */

#ifndef _Included_org_forstdb_TimedEnv
#define _Included_org_forstdb_TimedEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_TimedEnv
 * Method:    createTimedEnv
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_TimedEnv_createTimedEnv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_forstdb_TimedEnv
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_TimedEnv_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
