/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_FlinkEnv */

#ifndef _Included_org_forstdb_FlinkEnv
#define _Included_org_forstdb_FlinkEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_FlinkEnv
 * Method:    createFlinkEnv
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_FlinkEnv_createFlinkEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_forstdb_FlinkEnv
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_FlinkEnv_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
