/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_UInt64AddOperator */

#ifndef _Included_org_forstdb_UInt64AddOperator
#define _Included_org_forstdb_UInt64AddOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_UInt64AddOperator
 * Method:    newSharedUInt64AddOperator
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_UInt64AddOperator_newSharedUInt64AddOperator
  (JNIEnv *, jclass);

/*
 * Class:     org_forstdb_UInt64AddOperator
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_UInt64AddOperator_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
