/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_CassandraValueMergeOperator */

#ifndef _Included_org_forstdb_CassandraValueMergeOperator
#define _Included_org_forstdb_CassandraValueMergeOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_CassandraValueMergeOperator
 * Method:    newSharedCassandraValueMergeOperator
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_CassandraValueMergeOperator_newSharedCassandraValueMergeOperator
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_forstdb_CassandraValueMergeOperator
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_CassandraValueMergeOperator_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
