/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_SkipListMemTableConfig */

#ifndef _Included_org_forstdb_SkipListMemTableConfig
#define _Included_org_forstdb_SkipListMemTableConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef org_forstdb_SkipListMemTableConfig_DEFAULT_LOOKAHEAD
#define org_forstdb_SkipListMemTableConfig_DEFAULT_LOOKAHEAD 0LL
/*
 * Class:     org_forstdb_SkipListMemTableConfig
 * Method:    newMemTableFactoryHandle0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_SkipListMemTableConfig_newMemTableFactoryHandle0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
