/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_NativeComparatorWrapperTest_NativeStringComparatorWrapper */

#ifndef _Included_org_forstdb_NativeComparatorWrapperTest_NativeStringComparatorWrapper
#define _Included_org_forstdb_NativeComparatorWrapperTest_NativeStringComparatorWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_NativeComparatorWrapperTest_NativeStringComparatorWrapper
 * Method:    newStringComparator
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_NativeComparatorWrapperTest_00024NativeStringComparatorWrapper_newStringComparator
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
