/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_BackupEngine */

#ifndef _Included_org_forstdb_BackupEngine
#define _Included_org_forstdb_BackupEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_BackupEngine
 * Method:    open
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_BackupEngine_open
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    createNewBackup
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_createNewBackup
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    createNewBackupWithMetadata
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_createNewBackupWithMetadata
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    getBackupInfo
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_forstdb_BackupEngine_getBackupInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    getCorruptedBackups
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_forstdb_BackupEngine_getCorruptedBackups
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    garbageCollect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_garbageCollect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    purgeOldBackups
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_purgeOldBackups
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    deleteBackup
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_deleteBackup
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    restoreDbFromBackup
 * Signature: (JILjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_restoreDbFromBackup
  (JNIEnv *, jobject, jlong, jint, jstring, jstring, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    restoreDbFromLatestBackup
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_restoreDbFromLatestBackup
  (JNIEnv *, jobject, jlong, jstring, jstring, jlong);

/*
 * Class:     org_forstdb_BackupEngine
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_BackupEngine_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
