/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_Snapshot */

#ifndef _Included_org_forstdb_Snapshot
#define _Included_org_forstdb_Snapshot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_Snapshot
 * Method:    getSequenceNumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Snapshot_getSequenceNumber
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
