/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_Logger */

#ifndef _Included_org_forstdb_Logger
#define _Included_org_forstdb_Logger
#ifdef __cplusplus
extern "C" {
#endif
#undef org_forstdb_Logger_WITH_OPTIONS
#define org_forstdb_Logger_WITH_OPTIONS 0LL
#undef org_forstdb_Logger_WITH_DBOPTIONS
#define org_forstdb_Logger_WITH_DBOPTIONS 1LL
/*
 * Class:     org_forstdb_Logger
 * Method:    createNewLoggerOptions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Logger_createNewLoggerOptions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_Logger
 * Method:    createNewLoggerDbOptions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_Logger_createNewLoggerDbOptions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_Logger
 * Method:    setInfoLogLevel
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Logger_setInfoLogLevel
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_forstdb_Logger
 * Method:    infoLogLevel
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_forstdb_Logger_infoLogLevel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_Logger
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_Logger_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
