/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_WriteBatchTestInternalHelper */

#ifndef _Included_org_forstdb_WriteBatchTestInternalHelper
#define _Included_org_forstdb_WriteBatchTestInternalHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_WriteBatchTestInternalHelper
 * Method:    setSequence
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteBatchTestInternalHelper_setSequence
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_forstdb_WriteBatchTestInternalHelper
 * Method:    sequence
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_WriteBatchTestInternalHelper_sequence
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_forstdb_WriteBatchTestInternalHelper
 * Method:    append
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_WriteBatchTestInternalHelper_append
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
