/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_WriteBatch_Handler */

#ifndef _Included_org_forstdb_WriteBatch_Handler
#define _Included_org_forstdb_WriteBatch_Handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_WriteBatch_Handler
 * Method:    createNewHandler0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_WriteBatch_00024Handler_createNewHandler0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
