/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_AbstractCompactionFilter */

#ifndef _Included_org_forstdb_AbstractCompactionFilter
#define _Included_org_forstdb_AbstractCompactionFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_AbstractCompactionFilter
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_AbstractCompactionFilter_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
