/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_BloomFilter */

#ifndef _Included_org_forstdb_BloomFilter
#define _Included_org_forstdb_BloomFilter
#ifdef __cplusplus
extern "C" {
#endif
#undef org_forstdb_BloomFilter_DEFAULT_BITS_PER_KEY
#define org_forstdb_BloomFilter_DEFAULT_BITS_PER_KEY 10.0
/*
 * Class:     org_forstdb_BloomFilter
 * Method:    createNewBloomFilter
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_BloomFilter_createNewBloomFilter
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
