/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_test_TestableEventListener */

#ifndef _Included_org_forstdb_test_TestableEventListener
#define _Included_org_forstdb_test_TestableEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_test_TestableEventListener
 * Method:    invokeAllCallbacks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_test_TestableEventListener_invokeAllCallbacks
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
