/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_HashSkipListMemTableConfig */

#ifndef _Included_org_forstdb_HashSkipListMemTableConfig
#define _Included_org_forstdb_HashSkipListMemTableConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef org_forstdb_HashSkipListMemTableConfig_DEFAULT_BUCKET_COUNT
#define org_forstdb_HashSkipListMemTableConfig_DEFAULT_BUCKET_COUNT 1000000L
#undef org_forstdb_HashSkipListMemTableConfig_DEFAULT_BRANCHING_FACTOR
#define org_forstdb_HashSkipListMemTableConfig_DEFAULT_BRANCHING_FACTOR 4L
#undef org_forstdb_HashSkipListMemTableConfig_DEFAULT_HEIGHT
#define org_forstdb_HashSkipListMemTableConfig_DEFAULT_HEIGHT 4L
/*
 * Class:     org_forstdb_HashSkipListMemTableConfig
 * Method:    newMemTableFactoryHandle
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_HashSkipListMemTableConfig_newMemTableFactoryHandle
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
