/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_FlushOptions */

#ifndef _Included_org_forstdb_FlushOptions
#define _Included_org_forstdb_FlushOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_FlushOptions
 * Method:    newFlushOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_FlushOptions_newFlushOptions
  (JNIEnv *, jclass);

/*
 * Class:     org_forstdb_FlushOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_FlushOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_FlushOptions
 * Method:    setWaitForFlush
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_FlushOptions_setWaitForFlush
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_FlushOptions
 * Method:    waitForFlush
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_FlushOptions_waitForFlush
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_FlushOptions
 * Method:    setAllowWriteStall
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_FlushOptions_setAllowWriteStall
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_forstdb_FlushOptions
 * Method:    allowWriteStall
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_forstdb_FlushOptions_allowWriteStall
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
