/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_CassandraCompactionFilter */

#ifndef _Included_org_forstdb_CassandraCompactionFilter
#define _Included_org_forstdb_CassandraCompactionFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_CassandraCompactionFilter
 * Method:    createNewCassandraCompactionFilter0
 * Signature: (ZI)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_CassandraCompactionFilter_createNewCassandraCompactionFilter0
  (JNIEnv *, jclass, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
