/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_EnvFlinkTestSuite */

#ifndef _Included_org_forstdb_EnvFlinkTestSuite
#define _Included_org_forstdb_EnvFlinkTestSuite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_EnvFlinkTestSuite
 * Method:    buildNativeObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_EnvFlinkTestSuite_buildNativeObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_forstdb_EnvFlinkTestSuite
 * Method:    runAllTestSuites
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_EnvFlinkTestSuite_runAllTestSuites
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_EnvFlinkTestSuite
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_EnvFlinkTestSuite_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
