/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_AbstractEventListener */

#ifndef _Included_org_forstdb_AbstractEventListener
#define _Included_org_forstdb_AbstractEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_AbstractEventListener
 * Method:    createNewEventListener
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_AbstractEventListener_createNewEventListener
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_forstdb_AbstractEventListener
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_AbstractEventListener_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
