/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_MemoryUtil */

#ifndef _Included_org_forstdb_MemoryUtil
#define _Included_org_forstdb_MemoryUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_MemoryUtil
 * Method:    getApproximateMemoryUsageByType
 * Signature: ([J[J)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_forstdb_MemoryUtil_getApproximateMemoryUsageByType
  (JNIEnv *, jclass, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
