/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_RocksEnv */

#ifndef _Included_org_forstdb_RocksEnv
#define _Included_org_forstdb_RocksEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_RocksEnv
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_RocksEnv_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
