/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_AbstractTransactionNotifier */

#ifndef _Included_org_forstdb_AbstractTransactionNotifier
#define _Included_org_forstdb_AbstractTransactionNotifier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_AbstractTransactionNotifier
 * Method:    createNewTransactionNotifier
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_AbstractTransactionNotifier_createNewTransactionNotifier
  (JNIEnv *, jobject);

/*
 * Class:     org_forstdb_AbstractTransactionNotifier
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_forstdb_AbstractTransactionNotifier_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
