/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_BlockBasedTableConfig */

#ifndef _Included_org_forstdb_BlockBasedTableConfig
#define _Included_org_forstdb_BlockBasedTableConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_BlockBasedTableConfig
 * Method:    newTableFactoryHandle
 * Signature: (ZZZZBBDBZJJJIIIJZZZJZZIIZZBJI)J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_BlockBasedTableConfig_newTableFactoryHandle
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean, jbyte, jbyte, jdouble, jbyte, jboolean, jlong, jlong, jlong, jint, jint, jint, jlong, jboolean, jboolean, jboolean, jlong, jboolean, jboolean, jint, jint, jboolean, jboolean, jbyte, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
