/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_forstdb_AbstractTableFilter */

#ifndef _Included_org_forstdb_AbstractTableFilter
#define _Included_org_forstdb_AbstractTableFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_forstdb_AbstractTableFilter
 * Method:    createNewTableFilter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_forstdb_AbstractTableFilter_createNewTableFilter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
